name: Practice

on:
    push:
    workflow_dispatch:

jobs:
    say-hello-in-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello there"
            - run: echo "We going farther in this"

    say-hello-python:
        runs-on: ubuntu-latest
        steps:
            - run: print("Hello world")
              shell: python
    
    say-hello-in-bash-again:
        runs-on: ubuntu-latest
        needs:
            - say-hello-in-bash
            - say-hello-python
        steps:
            - run: echo "Hello there"
    final-hello:
        runs-on: ubuntu-latest
        needs:
            - say-hello-in-bash-again
        steps:
            - run: "Final hello in bash"