name: Practice

on:
    push:
    workflow_dispatch:

jobs:
    say-hello-in-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello there"

    say-hello-python:
        runs-on: ubuntu-latest
        steps:
            - run: print("Hello world")
              shell: python